baseURL = "https://exploration5.games/"
languageCode = "en-us"
title = "The Adventures of Exploration #5"
theme = "whiteplain"

footnotereturnlinkcontents = "â†©"
ignoreFiles = ["_template.md"]
preserveTaxonomyNames = true

copyright = "&copy; David Aronsohn 2017-2018"
description = "Come along with us for an Adventure"

# This is all displayed on author
[params.author]
    name = "David Aronsohn"
    twitter = "OnlyHaveCans"
    github = "OnlyHaveCans"
    gitlab = "OnlyHaveCans"

# Header
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Campaign Notes"
    url = "/campaign-notes/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3


# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
