baseURL = "https://exploration5.games"
languageCode = "en-us"
title = "Exploration #5"
theme = "hugo-theme-relearn"

[[menu.shortcuts]]
pre = '<i class="fa-brands fa-git-alt"></i> '
name = "Git Repo"
url = "https://onlyhavecans.works/www/exploration5.games"
weight = 10

[[menu.shortcuts]]
pre = '<i class="fa-fw fas fa-tags"></i> '
name = "Tags"
pageRef = "/tags"
weight = 30

[params]
themeVariant = "zen-light"
linkTitle = ""

[params.logo]
direction = "column"

[outputs]
home = ["html", "rss", "print"]
page = ["html", "rss", "print"]
section = ["html", "rss", "print"]

[markup.goldmark.parser.attribute]
block = true
